
from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(902, 771)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setStyleSheet("background-color: rgb(36, 31, 49);\n"
"color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.textArea = QtWidgets.QListView(self.centralwidget)
        self.textArea.setObjectName("textArea")
        self.gridLayout.addWidget(self.textArea, 1, 1, 1, 1)
        self.toggleButton = QtWidgets.QPushButton(self.centralwidget)
        self.toggleButton.setObjectName("toggleButton")
        self.gridLayout.addWidget(self.toggleButton, 0, 0, 1, 1)
        self.sidebarContainer = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sidebarContainer.sizePolicy().hasHeightForWidth())
        self.sidebarContainer.setSizePolicy(sizePolicy)
        self.sidebarContainer.setMaximumSize(QtCore.QSize(200, 16777215))
        self.sidebarContainer.setObjectName("sidebarContainer")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.sidebarContainer)
        self.verticalLayout.setObjectName("verticalLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.sidebarContainer)
        self.stackedWidget.setObjectName("stackedWidget")
        self.pageTranslations = QtWidgets.QWidget()
        self.pageTranslations.setObjectName("pageTranslations")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.pageTranslations)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_translation = QtWidgets.QLabel(self.pageTranslations)
        self.label_translation.setAlignment(QtCore.Qt.AlignCenter)
        self.label_translation.setObjectName("label_translation")
        self.verticalLayout_2.addWidget(self.label_translation)
        self.listTranslations = QtWidgets.QListWidget(self.pageTranslations)
        self.listTranslations.setObjectName("listTranslations")
        self.verticalLayout_2.addWidget(self.listTranslations)
        self.stackedWidget.addWidget(self.pageTranslations)
        self.pageBooks = QtWidgets.QWidget()
        self.pageBooks.setObjectName("pageBooks")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.pageBooks)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_book = QtWidgets.QLabel(self.pageBooks)
        self.label_book.setAlignment(QtCore.Qt.AlignCenter)
        self.label_book.setObjectName("label_book")
        self.verticalLayout_3.addWidget(self.label_book)
        self.listBooks = QtWidgets.QListWidget(self.pageBooks)
        self.listBooks.setObjectName("listBooks")
        self.verticalLayout_3.addWidget(self.listBooks)
        self.stackedWidget.addWidget(self.pageBooks)
        self.pageChapters = QtWidgets.QWidget()
        self.pageChapters.setObjectName("pageChapters")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.pageChapters)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QtWidgets.QLabel(self.pageChapters)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.listChapters = QtWidgets.QListWidget(self.pageChapters)
        self.listChapters.setObjectName("listChapters")
        self.verticalLayout_4.addWidget(self.listChapters)
        self.stackedWidget.addWidget(self.pageChapters)
        self.pageVerses = QtWidgets.QWidget()
        self.pageVerses.setObjectName("pageVerses")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.pageVerses)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_2 = QtWidgets.QLabel(self.pageVerses)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_5.addWidget(self.label_2)
        self.listVerses = QtWidgets.QListWidget(self.pageVerses)
        self.listVerses.setObjectName("listVerses")
        self.verticalLayout_5.addWidget(self.listVerses)
        self.stackedWidget.addWidget(self.pageVerses)
        self.verticalLayout.addWidget(self.stackedWidget)
        self.gridLayout.addWidget(self.sidebarContainer, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 902, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.textArea.setWordWrap(True)
        self.textArea.setModel(QtGui.QStandardItemModel())

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Bible"))
        self.toggleButton.setText(_translate("MainWindow", "<<"))
        self.label_translation.setText(_translate("MainWindow", "Translation"))
        self.label_book.setText(_translate("MainWindow", "Book"))
        self.label.setText(_translate("MainWindow", "Chapter"))
        self.label_2.setText(_translate("MainWindow", "Verse"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
